const tabList = [
  {
    name: 'wholeren',
    icon: require('@/assets/img/work/wholeren/logo.png'),
    title: '厚仁教育',
    time: '2019/3 - 至今',
    label:
      '前端负责人，app项目负责人，小程序集群负责人,熟悉技术栈：react(reactnative,taro,next),vue(nuxt,uniapp),flutter，cordova 等',
    con: [
      {
        name: 'app开发',
        duty: '前端独立开发，项目流程控制',
        stack: 'cordova1.0，ReactNative2.0，flutter3.0(正在策划)',
        hard: '业务对接 / 需求归纳整理 / 架构设计 / 更新策略 / 消息推送 / 测试发布 / 数据埋点 / 微信和指纹登录 / 国际化等',
      },
      {
        name: 'erp-fits 企业管理系统',
        duty: 'fits 平台前端实现',
        stack: 'react+procomponent+formily',
        hard: 'antdesign 及其周边熟练应用 / 项目分包管理 / formily schema 运用',
      },
      {
        name: 'C 端网站 重构企业各部门对外网站',
        duty: '对接市场，确定需求，独立开发实现',
        stack: 'nuxt 服务端渲染 / spa+vue',
        hard: 'seo 优化 / 组件封装',
      },
      {
        name: '小程序集群',
        duty: '探讨需求+前端独立开发',
        stack: '主 Taro 兼 Uniapp',
        hard: '微信功能对接 / 各平台兼容',
      },
    ],
  },
  {
    name: 'xunfei',
    icon: require('@/assets/img/work/xunfei/logo.png'),
    title: '科大讯飞',
    time: '2018/3 - 2019/3',
    label: '前期单个项目维护，后期泉山项目群负责人：+项目广度，+Vue 深入理解，+前端小组工作管理',
    con: [
      {
        name: 'NW 桌面程序',
        duty: '已有项目添加新需求+前端独立开发',
        stack: 'nw+node',
        hard: ' 熟悉 nw 的 api',
      },
      {
        name: 'Egret 阿尔法蛋小游戏',
        duty: '已有项目添加新需求',
        stack: 'Egret+Typescript',
        hard: '熟悉 Egret api 和动画逻辑',
      },
      {
        name: '泉山教师成长档案',
        duty: '前端负责人',
        stack: 'Vue 全家桶 / 权限路由 / Echarts 地图',
        hard: 'vue相关',
      },
    ],
  },
  {
    name: 'yryz',
    icon: require('@/assets/img/work/yryz/logo.png'),
    title: '悠然一指',
    time: '2017/3 - 2018/3',
    label: '负责App单个模块：+RN，+JS，+Vue，+前端基础',
    con: [
      {
        name: 'APP 悠然一指 / 圈乎',
        duty: '首页+文章详情页+评论点赞收藏',
        stack: 'ReactNative',
        hard: '嵌套 tab / 首屏体验 / ui 组件的封装',
      },
      {
        name: 'h5+静态 页面',
        duty: '输出 ui 页面',
        stack: 'vue',
        hard: '无',
      },
    ],
  },
  {
    name: 'yunli',
    icon: require('@/assets/img/work/yunli/logo.png'),
    title: '云里服务',
    time: '2016/10 - 2017/3',
    label: '入门',
    con: [
      {
        name: '微信小程序',
        duty: '小程序页面编写',
        stack: '微信原生',
        hard: '无',
      },
      {
        name: 'h5+静态 页面',
        duty: '输出 ui 页面',
        stack: 'vue',
        hard: '无',
      },
    ],
  },
];
const projectList = [
  {
    name: '体育类App',
    stack: ['react-native'],
    type: ['app'],
    label: '利用RN独立开发体育类App，包含直播和通信，上线ios和安卓平台',
    thumb: require('@/assets/img/project/app/sport/thumb.png'),
    img: [
      require('@/assets/img/project/app/sport/thumb.png'),
      require('@/assets/img/project/app/sport/1.png'),
      require('@/assets/img/project/app/sport/2.png'),
      require('@/assets/img/project/app/sport/3.png'),
    ],
  },
  {
    name: 'RN厚仁教育app',
    stack: ['react-native'],
    type: ['app'],
    label: '利用RN独立开发商用APP,用于企业用户的信息对接，课程管理。上线ios和安卓平台',
    thumb: require('@/assets/img/project/app/wholeren/thumb.png'),
    img: [
      require('@/assets/img/project/app/wholeren/thumb.png'),
      require('@/assets/img/project/app/wholeren/1.png'),
      require('@/assets/img/project/app/wholeren/2.png'),
      require('@/assets/img/project/app/wholeren/3.png'),
      require('@/assets/img/project/app/wholeren/4.png'),
      require('@/assets/img/project/app/wholeren/5.png'),
      require('@/assets/img/project/app/wholeren/6.png'),
      require('@/assets/img/project/app/wholeren/7.png'),
      require('@/assets/img/project/app/wholeren/8.png'),
      require('@/assets/img/project/app/wholeren/9.png'),
      require('@/assets/img/project/app/wholeren/10.png'),
      require('@/assets/img/project/app/wholeren/11.png'),
      require('@/assets/img/project/app/wholeren/12.png'),
      require('@/assets/img/project/app/wholeren/13.png'),
      require('@/assets/img/project/app/wholeren/14.png'),
      require('@/assets/img/project/app/wholeren/15.png'),
      require('@/assets/img/project/app/wholeren/16.png'),
      require('@/assets/img/project/app/wholeren/17.png'),
      require('@/assets/img/project/app/wholeren/18.png'),
      require('@/assets/img/project/app/wholeren/19.png'),
      require('@/assets/img/project/app/wholeren/20.png'),
      require('@/assets/img/project/app/wholeren/21.png'),
      require('@/assets/img/project/app/wholeren/22.png'),
      require('@/assets/img/project/app/wholeren/23.png'),
      require('@/assets/img/project/app/wholeren/24.png'),
      require('@/assets/img/project/app/wholeren/25.png'),
      require('@/assets/img/project/app/wholeren/26.png'),
    ],
  },
  {
    name: 'RN开发圈乎App',
    stack: ['react-native'],
    type: ['app'],
    label: '利用RN开发商用APP,主要负责首页，文章详情页页面逻辑,上线ios和安卓平台',
    thumb: require('@/assets/img/project/app/quanhu/thumb.png'),
    img: [
      require('@/assets/img/project/app/quanhu/thumb.png'),
      require('@/assets/img/project/app/quanhu/1.png'),
      require('@/assets/img/project/app/quanhu/2.png'),
      require('@/assets/img/project/app/quanhu/3.png'),
      require('@/assets/img/project/app/quanhu/4.png'),
      require('@/assets/img/project/app/quanhu/5.png'),
      require('@/assets/img/project/app/quanhu/6.png'),
      require('@/assets/img/project/app/quanhu/7.png'),
    ],
  },
  {
    name: 'RN开发悠然一指App',
    stack: ['react-native'],
    type: ['app'],
    label: '利用RN开发商用APP,主要负责首页，评论点赞等功能模块,上线ios和安卓平台',
    thumb: require('@/assets/img/project/app/yryz/thumb.png'),
    img: [
      require('@/assets/img/project/app/yryz/thumb.png'),
      require('@/assets/img/project/app/yryz/1.png'),
      require('@/assets/img/project/app/yryz/2.png'),
      require('@/assets/img/project/app/yryz/3.png'),
      require('@/assets/img/project/app/yryz/4.png'),
      require('@/assets/img/project/app/yryz/5.png'),
      require('@/assets/img/project/app/yryz/6.png'),
      require('@/assets/img/project/app/yryz/7.png'),
      require('@/assets/img/project/app/yryz/8.png'),
      require('@/assets/img/project/app/yryz/9.png'),
      require('@/assets/img/project/app/yryz/10.png'),
      require('@/assets/img/project/app/yryz/11.png'),
      require('@/assets/img/project/app/yryz/12.png'),
      require('@/assets/img/project/app/yryz/13.png'),
    ],
  },
  {
    name: '厚仁服务小程序',
    stack: ['taro'],
    type: ['小程序'],
    label: '针对所有C端用户开发的公司业务介绍型小程序，同时发布微信和头条',
    thumb: require('@/assets/img/project/applets/wholeren-fuwu/thumb.png'),
    img: [
      require('@/assets/img/project/app/sport/thumb.png'),
      require('@/assets/img/project/app/sport/1.png'),
      require('@/assets/img/project/app/sport/2.png'),
      require('@/assets/img/project/app/sport/3.png'),
    ],
  },
  {
    name: '厚仁留学微信小程序',
    stack: ['taro'],
    type: ['小程序'],
    label: '针对所有C端用户，提供美国大学疫情数据，同时通过nuxt开发了更丰富的网页版本',
    thumb: require('@/assets/img/project/applets/wholeren-liuxue/thumb.png'),
    img: [
      require('@/assets/img/project/app/sport/thumb.png'),
      require('@/assets/img/project/app/sport/1.png'),
      require('@/assets/img/project/app/sport/2.png'),
      require('@/assets/img/project/app/sport/3.png'),
    ],
  },
  {
    name: '厚仁学生中心微信小程序',
    stack: ['taro'],
    type: ['小程序'],
    label: '针对所有付费用户，提供日常管理，服务跟踪，申请反馈等功能',
    thumb: require('@/assets/img/project/applets/wholeren-student/thumb.png'),
    img: [
      require('@/assets/img/project/app/sport/thumb.png'),
      require('@/assets/img/project/app/sport/1.png'),
      require('@/assets/img/project/app/sport/2.png'),
      require('@/assets/img/project/app/sport/3.png'),
    ],
  },
  {
    name: '厚仁导师中心微信小程序',
    stack: ['taro'],
    type: ['小程序'],
    label: '针对公司服务导师，提供学生管理，服务跟踪等功能',
    thumb: require('@/assets/img/project/applets/wholeren-teacher/thumb.png'),
    img: [
      require('@/assets/img/project/app/sport/thumb.png'),
      require('@/assets/img/project/app/sport/1.png'),
      require('@/assets/img/project/app/sport/2.png'),
      require('@/assets/img/project/app/sport/3.png'),
    ],
  },
  {
    name: '留美导师专栏',
    stack: ['taro'],
    type: ['小程序'],
    label: '针对C端用户，提供留学资讯',
    thumb: require('@/assets/img/project/applets/wholeren-blog/thumb.png'),
    img: [
      require('@/assets/img/project/app/sport/thumb.png'),
      require('@/assets/img/project/app/sport/1.png'),
      require('@/assets/img/project/app/sport/2.png'),
      require('@/assets/img/project/app/sport/3.png'),
    ],
  },
  {
    name: 'fits-erp企业后台管理平台',
    stack: ['react', 'golang'],
    type: ['网站', '后端'],
    label: '针对公司业务，定制企业后台管理平台',
    thumb: require('@/assets/img/project/web/fits/thumb.png'),
    img: [
      require('@/assets/img/project/web/fits/thumb.png'),
      require('@/assets/img/project/web/fits/1.png'),
      require('@/assets/img/project/web/fits/2.png'),
      require('@/assets/img/project/web/fits/3.png'),
      require('@/assets/img/project/web/fits/4.png'),
      require('@/assets/img/project/web/fits/5.png'),
      require('@/assets/img/project/web/fits/6.png'),
    ],
  },
  {
    name: '美国校园疫情网',
    stack: ['vue', 'nuxt'],
    type: ['网站'],
    label: '利用RN独立开发厚仁教育商用APP,用于企业用户的信息对接，课程管理。',
    thumb: require('@/assets/img/project/web/covid/thumb.png'),
    img: [
      require('@/assets/img/project/web/covid/thumb.png'),
      require('@/assets/img/project/web/covid/1.png'),
      require('@/assets/img/project/web/covid/2.png'),
      require('@/assets/img/project/web/covid/3.png'),
      require('@/assets/img/project/web/covid/4.png'),
      require('@/assets/img/project/web/covid/5.png'),
      require('@/assets/img/project/web/covid/6.png'),
      require('@/assets/img/project/web/covid/7.png'),
      require('@/assets/img/project/web/covid/8.png'),
      require('@/assets/img/project/web/covid/9.png'),
      require('@/assets/img/project/web/covid/10.png'),
    ],
  },
  {
    name: '美国高校排名网',
    stack: ['vue', 'nuxt'],
    type: ['网站'],
    label: '利用RN独立开发厚仁教育商用APP,用于企业用户的信息对接，课程管理。',
    thumb: require('@/assets/img/project/web/school/thumb.png'),
    img: [
      require('@/assets/img/project/web/school/thumb.png'),
      require('@/assets/img/project/web/school/1.png'),
      require('@/assets/img/project/web/school/2.png'),
    ],
  },
  {
    name: '订单支付',
    stack: ['vue', 'nuxt'],
    type: ['网站'],
    label: '利用RN独立开发厚仁教育商用APP,用于企业用户的信息对接，课程管理。',
    thumb: require('@/assets/img/project/web/shop/thumb.png'),
    img: [
      require('@/assets/img/project/web/shop/thumb.png'),
      require('@/assets/img/project/web/shop/1.png'),
      require('@/assets/img/project/web/shop/2.png'),
      require('@/assets/img/project/web/shop/3.png'),
      require('@/assets/img/project/web/shop/4.png'),
      require('@/assets/img/project/web/shop/5.png'),
    ],
  },
  {
    name: '教师成长档案',
    stack: ['vue'],
    type: ['网站'],
    label: '利用RN独立开发厚仁教育商用APP,用于企业用户的信息对接，课程管理。',
    thumb: require('@/assets/img/project/web/teacher-admin/thumb.png'),
    img: [
      require('@/assets/img/project/web/teacher-admin/thumb.png'),
      require('@/assets/img/project/web/teacher-admin/1.png'),
      require('@/assets/img/project/web/teacher-admin/2.png'),
      require('@/assets/img/project/web/teacher-admin/3.png'),
      require('@/assets/img/project/web/teacher-admin/4.png'),
      require('@/assets/img/project/web/teacher-admin/5.png'),
      require('@/assets/img/project/web/teacher-admin/6.png'),
      require('@/assets/img/project/web/teacher-admin/7.png'),
      require('@/assets/img/project/web/teacher-admin/8.png'),
    ],
  },
  {
    name: '音乐播放器',
    stack: ['vue'],
    type: ['网站'],
    label: '利用RN独立开发厚仁教育商用APP,用于企业用户的信息对接，课程管理。',
    thumb: require('@/assets/img/project/web/music/thumb.png'),
    img: [
      require('@/assets/img/project/web/music/thumb.png'),
      require('@/assets/img/project/web/music/1.png'),
      require('@/assets/img/project/web/music/2.png'),
      require('@/assets/img/project/web/music/3.png'),
      require('@/assets/img/project/web/music/4.png'),
      require('@/assets/img/project/web/music/5.png'),
      require('@/assets/img/project/web/music/6.png'),
      require('@/assets/img/project/web/music/7.png'),
      require('@/assets/img/project/web/music/8.png'),
      require('@/assets/img/project/web/music/9.png'),
    ],
  },
  {
    name: 'Nw实现桌面程序',
    stack: ['nw'],
    type: ['电脑桌面程序'],
    label: '利用RN独立开发厚仁教育商用APP,用于企业用户的信息对接，课程管理。',
    thumb: require('@/assets/img/project/computer/nw/thumb.png'),
    img: [
      require('@/assets/img/project/computer/nw/thumb.png'),
      require('@/assets/img/project/computer/nw/1.png'),
      require('@/assets/img/project/computer/nw/2.png'),
      require('@/assets/img/project/computer/nw/3.png'),
      require('@/assets/img/project/computer/nw/4.png'),
      require('@/assets/img/project/computer/nw/5.png'),
      require('@/assets/img/project/computer/nw/6.png'),
    ],
  },
  {
    name: 'Egret白鹭引擎练手小鸟飞飞',
    stack: ['Egret'],
    type: ['小游戏'],
    label: '利用RN独立开发厚仁教育商用APP,用于企业用户的信息对接，课程管理。',
    thumb: require('@/assets/img/project/game/bird/thumb.png'),
    img: [require('@/assets/img/project/game/bird/thumb.png'), require('@/assets/img/project/game/bird/1.png')],
  },
  {
    name: 'Node实现微信公众号后台',
    stack: ['node'],
    type: ['后端'],
    label: '利用RN独立开发厚仁教育商用APP,用于企业用户的信息对接，课程管理。',
    thumb: require('@/assets/img/project/bs/node/thumb.png'),
    img: [
      require('@/assets/img/project/app/sport/thumb.png'),
      require('@/assets/img/project/app/sport/1.png'),
      require('@/assets/img/project/app/sport/2.png'),
      require('@/assets/img/project/app/sport/3.png'),
    ],
  },
  {
    name: '微信企业办公小程序',
    stack: ['uniapp', 'java'],
    type: ['后端', '小程序'],
    label: '利用RN独立开发厚仁教育商用APP,用于企业用户的信息对接，课程管理。',
    thumb: require('@/assets/img/project/bs/java/thumb.png'),
    img: [
      require('@/assets/img/project/app/sport/thumb.png'),
      require('@/assets/img/project/app/sport/1.png'),
      require('@/assets/img/project/app/sport/2.png'),
      require('@/assets/img/project/app/sport/3.png'),
    ],
  },
];
const regex = {
  tel: /^1[3-9]\d{9}$/, // 手机号
  china: /^(\+?0?86-?)?1[345789]\d{9}$/, // 中国手机号
  americal: /^(\+?1)?[2-9]\d{2}[2-9](?!11)\d{6}$/, // 美国手机号
  email: /^[A-Za-z0-9]+([_\-.][A-Za-z0-9]+)*@([A-Za-z0-9-]+\.)+[A-Za-z]{2,6}$/i, // 邮箱
};

export { tabList, regex, projectList };
