const tabList = [
  {
    name: 'astriddao',
    title: 'Astriddao',
    time: '2022/3 - 至今',
    label: ['sio2项目前端负责人，Astriddao协助开发', '熟悉技术栈：Web3，钱包连接，合约连接，React，Next 等'],
    con: [
      {
        name: 'Noname Monster前端开发',
        duty: '前端独立开发',
        stack: 'Web3，MetaMask，React，Next',
        hard: '合约对接',
        detail: {
          label: 'noname测试地址',
          link: 'https://dev-app.noname.monster',
        },
      },
      {
        name: 'Sio2前端开发',
        duty: '前端独立开发',
        stack: 'Web3，MetaMask，React，Next',
        hard: '合约对接',
        detail: {
          label: 'sio2测试地址',
          link: 'https://shibuya.sio2.finance',
        },
      },
      {
        name: 'Astriddao前端开发',
        duty: '协助Astriddao开发',
        stack: 'web3，react',
        hard: '熟悉web3钱包连接',
        detail: {
          label: 'astriddao线上地址',
          link: 'https://app.astriddao.xyz',
        },
      },
    ],
  },
  {
    name: 'wholeren',
    title: '厚仁教育',
    time: '2019/3 - 至今',
    label: [
      '前端负责人，app项目负责人，小程序集群负责人',
      '熟悉技术栈：react(reactnative,taro,next),vue(nuxt,uniapp),flutter，cordova 等',
    ],
    con: [
      {
        name: 'app开发',
        duty: '前端独立开发，项目流程控制',
        stack: 'cordova1.0，ReactNative2.0，flutter3.0(正在策划)',
        hard: '业务对接 / 需求归纳整理 / 架构设计 / 更新策略 / 消息推送 / 测试发布 / 数据埋点 / 微信和指纹登录 / 国际化等',
        detail: {
          label: 'google play或者app store搜索厚仁教育',
        },
      },
      {
        name: 'erp-fits 企业管理系统',
        duty: 'fits 平台前端实现',
        stack: 'react+procomponent+formily',
        hard: 'antdesign 及其周边熟练应用 / 项目分包管理 / formily schema 运用',
        detail: {
          label: 'fits平台测试站 https://fitsdev.wholerengroup.com',
          link: 'https://fitsdev.wholerengroup.com',
        },
      },
      {
        name: 'C 端网站 重构企业各部门对外网站',
        duty: '对接市场，确定需求，独立开发实现',
        stack: 'nuxt 服务端渲染 / spa+vue',
        hard: 'seo 优化 / 组件封装',
        detail: {
          label: '疫情网等相关网站 https://c.wholeren.com/',
          link: 'https://c.wholeren.com/',
        },
      },
      {
        name: '小程序集群',
        duty: '探讨需求+前端独立开发',
        stack: '主 Taro 兼 Uniapp',
        hard: '微信功能对接 / 各平台兼容',
        detail: {
          label: '厚仁服务，厚仁留学，留美导师，厚仁学生中心，厚仁导师中心等',
        },
      },
    ],
  },
  {
    name: 'xunfei',
    title: '科大讯飞',
    time: '2018/3 - 2019/3',
    label: ['前期单个项目维护，后期泉山项目群负责人', '+项目广度，+Vue 深入理解，+前端小组工作管理'],
    con: [
      {
        name: 'NW 桌面程序',
        duty: '已有项目添加新需求+前端独立开发',
        stack: 'nw+node',
        hard: ' 熟悉 nw 的 api',
      },
      {
        name: 'Egret 阿尔法蛋小游戏',
        duty: '已有项目添加新需求',
        stack: 'Egret+Typescript',
        hard: '熟悉 Egret api 和动画逻辑',
      },
      {
        name: '泉山教师成长档案',
        duty: '前端负责人',
        stack: 'Vue 全家桶 / 权限路由 / Echarts 地图',
        hard: 'vue相关',
      },
    ],
  },
  {
    name: 'yryz',
    title: '悠然一指',
    time: '2017/3 - 2018/3',
    label: ['负责App单个模块,', '+RN，+JS，+Vue，+前端基础'],
    con: [
      {
        name: 'APP 悠然一指 / 圈乎',
        duty: '首页+文章详情页+评论点赞收藏',
        stack: 'ReactNative',
        hard: '嵌套 tab / 首屏体验 / ui 组件的封装',
      },
      {
        name: 'h5+静态 页面',
        duty: '输出 ui 页面',
        stack: 'vue',
        hard: '无',
      },
    ],
  },
  {
    name: 'yunli',
    title: '云里服务',
    time: '2016/10 - 2017/3',
    label: ['入门'],
    con: [
      {
        name: '微信小程序',
        duty: '小程序页面编写',
        stack: '微信原生',
        hard: '无',
      },
      {
        name: 'h5+静态 页面',
        duty: '输出 ui 页面',
        stack: 'vue',
        hard: '无',
      },
    ],
  },
];
const tabListEn = [
  {
    name: 'astriddao',
    title: 'Astriddao',
    time: '2022/3 - present',
    label: [
      'sio2 project front-end leader, Astriddao assists in development',
      'Familiar with technology stack: Web3, wallet connection, contract connection, React, Next, etc.',
    ],
    con: [
      {
        name: 'Noname Monster front-end development',
        duty: 'Front-end independent development',
        stack: 'Web3, MetaMask, React, Next',
        hard: 'Contract docking',
        details: {
          label: 'noname test address',
          link: 'https://dev-app.noname.monster',
        },
      },
      {
        name: 'Sio2 front-end development',
        duty: 'Front-end independent development',
        stack: 'Web3, MetaMask, React, Next',
        hard: 'Contract connection',
        detail: {
          label: 'sio2 test address',
          link: 'https://shibuya.sio2.finance',
        },
      },
      {
        name: 'Astriddao front-end development',
        duty: 'Assist Astriddao development',
        stack: 'web3, react',
        hard: 'Familiar with web3 wallet connection',
        detail: {
          label: 'astriddao online address',
          link: 'https://app.astriddao.xyz',
        },
      },
    ],
  },
  {
    name: 'wholeren',
    title: 'Benevolence Education',
    time: '2019/3 - present',
    label: [
      'Front-end leader, app project leader, applet cluster leader',
      'Familiar with the technology stack: react (reactnative, taro, next), vue (nuxt, uniapp), flutter, cordova, etc.',
    ],
    con: [
      {
        name: 'app development',
        duty: 'Independent front-end development, project process control',
        stack: 'cordova1.0, ReactNative2.0, flutter3.0 (planning)',
        hard: 'Business docking/requirements sorting/architecture design/update strategy/message push/test release/data embedding/WeChat and fingerprint login/internationalization, etc.',
        detail: {
          label: 'Google play or app store search for Houren Education',
        },
      },
      {
        name: 'erp-fits enterprise management system',
        duty: 'fits platform front-end implementation',
        stack: 'react+procomponent+formily',
        hard: 'Antdesign and its surrounding proficient application / project subcontract management / formily schema application',
        detail: {
          label: 'fits platform test station https://fitsdev.wholerengroup.com',
          link: 'https://fitsdev.wholerengroup.com',
        },
      },
      {
        name: 'C-side website rebuilds the external websites of various departments of the enterprise',
        duty: 'Connect to the market, determine demand, and develop and implement independently',
        stack: 'nuxt server-side rendering / spa+vue',
        hard: 'seo optimization / component packaging',
        detail: {
          label: 'Epidemic website and other related websites https://c.wholeren.com/',
          link: 'https://c.wholeren.com/',
        },
      },
      {
        name: 'Mini Program Cluster',
        duty: 'Discuss requirements + independent front-end development',
        stack: 'Main Taro and Uniapp',
        hard: 'WeChat function docking / compatible with each platform',
        detail: {
          label:
            'HouRen Service, HouRen Study Abroad, American Tutor, HouRen Student Center, HouRen Tutor Center, etc.',
        },
      },
    ],
  },
  {
    name: 'xunfei',
    title: 'IFLYTEK',
    time: '2018/3 - 2019/3',
    label: [
      'In the early stage of single project maintenance, in the later stage of Quanshan project group leader',
      '+ project breadth, + Vue in-depth understanding, + front-end team work management',
    ],
    con: [
      {
        name: 'NW Desktop Program',
        duty: 'Add new requirements to existing projects + independent front-end development',
        stack: 'nw+node',
        hard: "Familiar with nw's api",
      },
      {
        name: 'Egret Alpha Egg Game',
        duty: 'Add new requirements to existing projects',
        stack: 'Egret+Typescript',
        hard: 'Familiar with Egret api and animation logic',
      },
      {
        name: 'Quanshan Teacher Growth File',
        duty: 'Front-end person in charge',
        stack: 'Vue Family Bucket / Permission Routing / Echarts Map',
        hard: 'vue related',
      },
    ],
  },
  {
    name: 'yryz',
    title: 'Leisurely Finger',
    time: '2017/3 - 2018/3',
    label: ['Responsible for a single module of the App,', '+RN, +JS, +Vue, + front-end foundation'],
    con: [
      {
        name: 'APP leisurely finger / circle',
        duty: 'Homepage + Article details page + Comments, likes and favorites',
        stack: 'ReactNative',
        hard: 'Nested tab / first screen experience / encapsulation of ui components',
      },
      {
        name: 'h5+static page',
        duty: 'output ui page',
        stack: 'vue',
        hard: 'none',
      },
    ],
  },
  {
    name: 'yunli',
    title: 'Cloud service',
    time: '2016/10 - 2017/3',
    label: ['Getting started'],
    con: [
      {
        name: 'WeChat applet',
        duty: 'Mini program page writing',
        stack: 'WeChat native',
        hard: 'none',
      },
      {
        name: 'h5+static page',
        duty: 'output ui page',
        stack: 'vue',
        hard: 'none',
      },
    ],
  },
];
const projectList = [
  {
    name: 'noname monster',
    stack: ['react web3'],
    type: ['网站'],
    label: '开发web3 nft交易平台',
    thumb: require('@/assets/img/project/web/noname/thumb.png'),
    img: [
      require('@/assets/img/project/web/noname/1.png'),
      require('@/assets/img/project/web/noname/2.png'),
      require('@/assets/img/project/web/noname/3.png'),
      require('@/assets/img/project/web/noname/4.png'),
      require('@/assets/img/project/web/noname/5.png'),
      require('@/assets/img/project/web/noname/6.png'),
    ],
    con: ['开发周期,4个月', '我负责,前端独立开发', '线上链接,http://dev-app.noname.monster', '相关难点,seaport方法'],
  },
  {
    name: 'sio2',
    stack: ['react web3'],
    type: ['网站'],
    label: '开发web3线上借贷平台',
    thumb: require('@/assets/img/project/web/sio2/thumb.png'),
    img: [
      require('@/assets/img/project/web/sio2/2.png'),
      require('@/assets/img/project/web/sio2/3.png'),
      require('@/assets/img/project/web/sio2/4.png'),
      require('@/assets/img/project/web/sio2/5.png'),
      require('@/assets/img/project/web/sio2/6.png'),
    ],
    con: ['开发周期,2个月', '我负责,前端独立开发', '线上链接,http://shibuya.sio2.finance', '相关难点,合约集成'],
  },
  {
    name: 'astriddao',
    stack: ['react web3'],
    type: ['网站'],
    label: '开发web3线上虚拟币平台',
    thumb: require('@/assets/img/project/web/astriddao/thumb.png'),
    img: [
      require('@/assets/img/project/web/astriddao/1.png'),
      require('@/assets/img/project/web/astriddao/3.png'),
      require('@/assets/img/project/web/astriddao/4.png'),
      require('@/assets/img/project/web/astriddao/5.png'),
      require('@/assets/img/project/web/astriddao/6.png'),
    ],
    con: ['开发周期,1个月', '我负责,响应式适配', '线上链接,http://app.astriddao.xyz', '相关难点,theme-ui'],
  },
  {
    name: '体育类App',
    stack: ['react-native'],
    type: ['app'],
    label: '利用RN独立开发体育类App，包含直播和通信，上线ios和安卓平台',
    thumb: require('@/assets/img/project/app/sport/thumb.png'),
    img: [
      require('@/assets/img/project/app/sport/thumb.png'),
      require('@/assets/img/project/app/sport/1.png'),
      require('@/assets/img/project/app/sport/2.png'),
      require('@/assets/img/project/app/sport/3.png'),
    ],
    con: ['开发周期,1个月', '我负责,独立开发', '线上链接,暂无', '相关难点,集成即时通讯-集成图表-集成三方登录'],
  },
  {
    name: 'RN厚仁教育app',
    stack: ['react-native'],
    type: ['app'],
    label: '利用RN独立开发商用APP,用于企业用户的信息对接，课程管理。上线ios和安卓平台',
    thumb: require('@/assets/img/project/app/wholeren/thumb.png'),
    img: [
      require('@/assets/img/project/app/wholeren/thumb.png'),
      require('@/assets/img/project/app/wholeren/1.png'),
      require('@/assets/img/project/app/wholeren/2.png'),
      require('@/assets/img/project/app/wholeren/3.png'),
      require('@/assets/img/project/app/wholeren/4.png'),
      require('@/assets/img/project/app/wholeren/5.png'),
      require('@/assets/img/project/app/wholeren/6.png'),
      require('@/assets/img/project/app/wholeren/7.png'),
      require('@/assets/img/project/app/wholeren/8.png'),
      require('@/assets/img/project/app/wholeren/9.png'),
      require('@/assets/img/project/app/wholeren/10.png'),
      require('@/assets/img/project/app/wholeren/11.png'),
      require('@/assets/img/project/app/wholeren/12.png'),
      require('@/assets/img/project/app/wholeren/13.png'),
      require('@/assets/img/project/app/wholeren/14.png'),
      require('@/assets/img/project/app/wholeren/15.png'),
      require('@/assets/img/project/app/wholeren/16.png'),
      require('@/assets/img/project/app/wholeren/17.png'),
      require('@/assets/img/project/app/wholeren/18.png'),
      require('@/assets/img/project/app/wholeren/19.png'),
      require('@/assets/img/project/app/wholeren/20.png'),
      require('@/assets/img/project/app/wholeren/21.png'),
      require('@/assets/img/project/app/wholeren/22.png'),
      require('@/assets/img/project/app/wholeren/23.png'),
      require('@/assets/img/project/app/wholeren/24.png'),
      require('@/assets/img/project/app/wholeren/25.png'),
      require('@/assets/img/project/app/wholeren/26.png'),
    ],
  },
  {
    name: 'RN开发圈乎App',
    stack: ['react-native'],
    type: ['app'],
    label: '利用RN开发商用APP,主要负责首页，文章详情页页面逻辑,上线ios和安卓平台',
    thumb: require('@/assets/img/project/app/quanhu/thumb.png'),
    img: [
      require('@/assets/img/project/app/quanhu/thumb.png'),
      require('@/assets/img/project/app/quanhu/1.png'),
      require('@/assets/img/project/app/quanhu/2.png'),
      require('@/assets/img/project/app/quanhu/3.png'),
      require('@/assets/img/project/app/quanhu/4.png'),
      require('@/assets/img/project/app/quanhu/5.png'),
      require('@/assets/img/project/app/quanhu/6.png'),
      require('@/assets/img/project/app/quanhu/7.png'),
    ],
  },
  {
    name: 'RN开发悠然一指App',
    stack: ['react-native'],
    type: ['app'],
    label: '利用RN开发商用APP,主要负责首页，评论点赞等功能模块,上线ios和安卓平台',
    thumb: require('@/assets/img/project/app/yryz/thumb.png'),
    img: [
      require('@/assets/img/project/app/yryz/thumb.png'),
      require('@/assets/img/project/app/yryz/1.png'),
      require('@/assets/img/project/app/yryz/2.png'),
      require('@/assets/img/project/app/yryz/3.png'),
      require('@/assets/img/project/app/yryz/4.png'),
      require('@/assets/img/project/app/yryz/5.png'),
      require('@/assets/img/project/app/yryz/6.png'),
      require('@/assets/img/project/app/yryz/7.png'),
      require('@/assets/img/project/app/yryz/8.png'),
      require('@/assets/img/project/app/yryz/9.png'),
      require('@/assets/img/project/app/yryz/10.png'),
      require('@/assets/img/project/app/yryz/11.png'),
      require('@/assets/img/project/app/yryz/12.png'),
      require('@/assets/img/project/app/yryz/13.png'),
    ],
  },
  {
    name: '厚仁服务小程序',
    stack: ['taro'],
    type: ['小程序'],
    label: '针对所有C端用户开发的公司业务介绍型小程序，同时发布微信和头条',
    thumb: require('@/assets/img/project/applets/wholeren-fuwu/thumb.png'),
    img: [
      require('@/assets/img/project/applets/wholeren-fuwu/thumb.png'),
      require('@/assets/img/project/applets/wholeren-fuwu/1.png'),
      require('@/assets/img/project/applets/wholeren-fuwu/2.png'),
      require('@/assets/img/project/applets/wholeren-fuwu/3.png'),
      require('@/assets/img/project/applets/wholeren-fuwu/4.png'),
    ],
  },
  {
    name: '厚仁留学微信小程序',
    stack: ['taro'],
    type: ['小程序'],
    label: '针对所有C端用户，提供美国大学疫情数据，同时通过nuxt开发了更丰富的网页版本',
    thumb: require('@/assets/img/project/applets/wholeren-liuxue/thumb.png'),
    img: [
      require('@/assets/img/project/applets/wholeren-liuxue/thumb.png'),
      require('@/assets/img/project/applets/wholeren-liuxue/1.png'),
      require('@/assets/img/project/applets/wholeren-liuxue/2.png'),
      require('@/assets/img/project/applets/wholeren-liuxue/3.png'),
    ],
  },
  {
    name: '厚仁学生中心微信小程序',
    stack: ['taro'],
    type: ['小程序'],
    label: '针对所有付费用户，提供日常管理，服务跟踪，申请反馈等功能',
    thumb: require('@/assets/img/project/applets/wholeren-student/thumb.png'),
    img: [
      require('@/assets/img/project/applets/wholeren-student/thumb.png'),
      require('@/assets/img/project/applets/wholeren-student/1.png'),
      require('@/assets/img/project/applets/wholeren-student/2.png'),
      require('@/assets/img/project/applets/wholeren-student/3.png'),
      require('@/assets/img/project/applets/wholeren-student/4.png'),
      require('@/assets/img/project/applets/wholeren-student/5.png'),
      require('@/assets/img/project/applets/wholeren-student/6.png'),
      require('@/assets/img/project/applets/wholeren-student/7.png'),
      require('@/assets/img/project/applets/wholeren-student/8.png'),
      require('@/assets/img/project/applets/wholeren-student/9.png'),
      require('@/assets/img/project/applets/wholeren-student/10.png'),
    ],
  },
  {
    name: '厚仁导师中心微信小程序',
    stack: ['taro'],
    type: ['小程序'],
    label: '针对公司服务导师，提供学生管理，服务跟踪等功能',
    thumb: require('@/assets/img/project/applets/wholeren-teacher/thumb.png'),
    img: [
      require('@/assets/img/project/applets/wholeren-teacher/thumb.png'),
      require('@/assets/img/project/applets/wholeren-teacher/1.png'),
      require('@/assets/img/project/applets/wholeren-teacher/2.png'),
      require('@/assets/img/project/applets/wholeren-teacher/3.png'),
      require('@/assets/img/project/applets/wholeren-teacher/4.png'),
      require('@/assets/img/project/applets/wholeren-teacher/5.png'),
      require('@/assets/img/project/applets/wholeren-teacher/6.png'),
      require('@/assets/img/project/applets/wholeren-teacher/7.png'),
    ],
  },
  {
    name: '留美导师专栏',
    stack: ['taro'],
    type: ['小程序'],
    label: '针对C端用户，提供留学资讯',
    thumb: require('@/assets/img/project/applets/wholeren-blog/thumb.png'),
    img: [
      require('@/assets/img/project/applets/wholeren-blog/thumb.png'),
      require('@/assets/img/project/applets/wholeren-blog/1.png'),
      require('@/assets/img/project/applets/wholeren-blog/2.png'),
      require('@/assets/img/project/applets/wholeren-blog/3.png'),
      require('@/assets/img/project/applets/wholeren-blog/4.png'),
      require('@/assets/img/project/applets/wholeren-blog/5.png'),
    ],
  },
  {
    name: 'fits-erp企业后台管理平台',
    stack: ['react', 'golang'],
    type: ['网站', '后端'],
    label: '针对公司业务，定制企业后台管理平台',
    thumb: require('@/assets/img/project/web/fits/thumb.png'),
    img: [
      require('@/assets/img/project/web/fits/thumb.png'),
      require('@/assets/img/project/web/fits/1.png'),
      require('@/assets/img/project/web/fits/2.png'),
      require('@/assets/img/project/web/fits/3.png'),
      require('@/assets/img/project/web/fits/4.png'),
      require('@/assets/img/project/web/fits/5.png'),
      require('@/assets/img/project/web/fits/6.png'),
    ],
  },
  {
    name: '美国校园疫情网',
    stack: ['vue', 'nuxt'],
    type: ['网站'],
    label: '针对美国校园疫情，提供疫情数据和学校数据。使用nuxt保证良好的seo',
    thumb: require('@/assets/img/project/web/covid/thumb.png'),
    img: [
      require('@/assets/img/project/web/covid/thumb.png'),
      require('@/assets/img/project/web/covid/1.png'),
      require('@/assets/img/project/web/covid/2.png'),
      require('@/assets/img/project/web/covid/3.png'),
      require('@/assets/img/project/web/covid/4.png'),
      require('@/assets/img/project/web/covid/5.png'),
      require('@/assets/img/project/web/covid/6.png'),
      require('@/assets/img/project/web/covid/7.png'),
      require('@/assets/img/project/web/covid/8.png'),
      require('@/assets/img/project/web/covid/9.png'),
      require('@/assets/img/project/web/covid/10.png'),
    ],
  },
  {
    name: '美国高校排名网',
    stack: ['vue', 'nuxt'],
    type: ['网站'],
    label: '针对c端用户，提供高校排名数据，使用nuxt保证良好seo',
    thumb: require('@/assets/img/project/web/school/thumb.png'),
    img: [
      require('@/assets/img/project/web/school/thumb.png'),
      require('@/assets/img/project/web/school/1.png'),
      require('@/assets/img/project/web/school/2.png'),
    ],
  },
  {
    name: '订单支付',
    stack: ['vue', 'nuxt'],
    type: ['网站'],
    label: '使用vue开发的用户付费界面',
    thumb: require('@/assets/img/project/web/shop/thumb.png'),
    img: [
      require('@/assets/img/project/web/shop/thumb.png'),
      require('@/assets/img/project/web/shop/1.png'),
      require('@/assets/img/project/web/shop/2.png'),
      require('@/assets/img/project/web/shop/3.png'),
      require('@/assets/img/project/web/shop/4.png'),
      require('@/assets/img/project/web/shop/5.png'),
    ],
  },
  {
    name: '教师成长档案',
    stack: ['vue'],
    type: ['网站'],
    label: '使用vue开发的后台管理系统',
    thumb: require('@/assets/img/project/web/teacher-admin/thumb.png'),
    img: [
      require('@/assets/img/project/web/teacher-admin/thumb.png'),
      require('@/assets/img/project/web/teacher-admin/1.png'),
      require('@/assets/img/project/web/teacher-admin/2.png'),
      require('@/assets/img/project/web/teacher-admin/3.png'),
      require('@/assets/img/project/web/teacher-admin/4.png'),
      require('@/assets/img/project/web/teacher-admin/5.png'),
      require('@/assets/img/project/web/teacher-admin/6.png'),
      require('@/assets/img/project/web/teacher-admin/7.png'),
      require('@/assets/img/project/web/teacher-admin/8.png'),
    ],
  },
  {
    name: '音乐播放器',
    stack: ['vue'],
    type: ['网站'],
    label: '使用vue开发的音乐播放器（练手）',
    thumb: require('@/assets/img/project/web/music/thumb.png'),
    img: [
      require('@/assets/img/project/web/music/thumb.png'),
      require('@/assets/img/project/web/music/1.png'),
      require('@/assets/img/project/web/music/2.png'),
      require('@/assets/img/project/web/music/3.png'),
      require('@/assets/img/project/web/music/4.png'),
      require('@/assets/img/project/web/music/5.png'),
      require('@/assets/img/project/web/music/6.png'),
      require('@/assets/img/project/web/music/7.png'),
      require('@/assets/img/project/web/music/8.png'),
      require('@/assets/img/project/web/music/9.png'),
    ],
  },
  {
    name: 'Nw实现桌面程序',
    stack: ['nw'],
    type: ['电脑桌面程序'],
    label: '使用nw开发的新疆课堂课件桌面程序。',
    thumb: require('@/assets/img/project/computer/nw/thumb.png'),
    img: [
      require('@/assets/img/project/computer/nw/thumb.png'),
      require('@/assets/img/project/computer/nw/1.png'),
      require('@/assets/img/project/computer/nw/2.png'),
      require('@/assets/img/project/computer/nw/3.png'),
      require('@/assets/img/project/computer/nw/4.png'),
      require('@/assets/img/project/computer/nw/5.png'),
      require('@/assets/img/project/computer/nw/6.png'),
    ],
  },
  {
    name: 'Egret白鹭引擎练手小鸟飞飞',
    stack: ['Egret'],
    type: ['小游戏'],
    label: '使用Egret+Typescript开发阿尔法蛋上的幼儿园小游戏（小鸟飞飞为练手项目）',
    thumb: require('@/assets/img/project/game/bird/thumb.png'),
    img: [require('@/assets/img/project/game/bird/thumb.png'), require('@/assets/img/project/game/bird/1.png')],
  },
  {
    name: 'Node实现微信公众号后台',
    stack: ['node'],
    type: ['后端'],
    label: '使用node调用jssdk，网页端集成微信登录，付款等功能',
    thumb: require('@/assets/img/project/bs/node/thumb.png'),
    img: [
      require('@/assets/img/project/app/sport/thumb.png'),
      require('@/assets/img/project/app/sport/1.png'),
      require('@/assets/img/project/app/sport/2.png'),
      require('@/assets/img/project/app/sport/3.png'),
    ],
  },
  {
    name: '微信企业办公小程序',
    stack: ['uniapp', 'java'],
    type: ['后端', '小程序'],
    label: '使用java+uniapp，实现企业办公小程序（练手）',
    thumb: require('@/assets/img/project/bs/java/thumb.png'),
    img: [
      require('@/assets/img/project/app/sport/thumb.png'),
      require('@/assets/img/project/app/sport/1.png'),
      require('@/assets/img/project/app/sport/2.png'),
      require('@/assets/img/project/app/sport/3.png'),
    ],
  },
];
const projectListEn = [
  {
    name: 'noname monster',
    stack: ['react web3'],
    type: ['Website'],
    label: 'Develop web3 nft trading platform',
    thumb: require('@/assets/img/project/web/noname/thumb.png'),
    img: [
      require('@/assets/img/project/web/noname/1.png'),
      require('@/assets/img/project/web/noname/2.png'),
      require('@/assets/img/project/web/noname/3.png'),
      require('@/assets/img/project/web/noname/4.png'),
      require('@/assets/img/project/web/noname/5.png'),
      require('@/assets/img/project/web/noname/6.png'),
    ],
    con: [
      'Development cycle, 4 months',
      'I am responsible for, front-end independent development',
      'Online link, http://dev-app.noname.monster',
      'Related difficulties, seaport method',
    ],
  },
  {
    name: 'sio2',
    stack: ['react web3'],
    type: ['Website'],
    label: 'Development of web3 online lending platform',
    thumb: require('@/assets/img/project/web/sio2/thumb.png'),
    img: [
      require('@/assets/img/project/web/sio2/2.png'),
      require('@/assets/img/project/web/sio2/3.png'),
      require('@/assets/img/project/web/sio2/4.png'),
      require('@/assets/img/project/web/sio2/5.png'),
      require('@/assets/img/project/web/sio2/6.png'),
    ],
    con: [
      'Development cycle,2 months',
      'I am responsible for,independent front-end development',
      'Online link,http://shibuya.sio2.finance',
      'Related difficulties,contract integration',
    ],
  },
  {
    name: 'astriddao',
    stack: ['react web3'],
    type: ['Website'],
    label: 'Development of web3 online virtual currency platform',
    thumb: require('@/assets/img/project/web/astriddao/thumb.png'),
    img: [
      require('@/assets/img/project/web/astriddao/1.png'),
      require('@/assets/img/project/web/astriddao/3.png'),
      require('@/assets/img/project/web/astriddao/4.png'),
      require('@/assets/img/project/web/astriddao/5.png'),
      require('@/assets/img/project/web/astriddao/6.png'),
    ],
    con: [
      'Development cycle,1 month',
      'I am responsible for,responsive adaptation',
      'Online link,http://app.astriddao.xyz',
      'Related difficulties,theme-ui',
    ],
  },
  {
    name: 'Sports App',
    stack: ['react-native'],
    type: ['App'],
    label:
      'Use RN to independently develop sports apps, including live broadcast and communication, and launch ios and Android platforms',
    thumb: require('@/assets/img/project/app/sport/thumb.png'),
    img: [
      require('@/assets/img/project/app/sport/thumb.png'),
      require('@/assets/img/project/app/sport/1.png'),
      require('@/assets/img/project/app/sport/2.png'),
      require('@/assets/img/project/app/sport/3.png'),
    ],
    con: [
      'Development cycle: 1 month',
      'I am responsible for: independent development',
      'Online link: No currently available',
      'Related difficulties: integrated instant messaging - integrated charts - integrated three-party login',
    ],
  },
  {
    name: 'RN Huren Education app',
    stack: ['react-native'],
    type: ['App'],
    label:
      'Using RN to independently develop a commercial APP, which is used for information connection and course management of enterprise users. Launched on ios and Android platforms',
    thumb: require('@/assets/img/project/app/wholeren/thumb.png'),
    img: [
      require('@/assets/img/project/app/wholeren/thumb.png'),
      require('@/assets/img/project/app/wholeren/1.png'),
      require('@/assets/img/project/app/wholeren/2.png'),
      require('@/assets/img/project/app/wholeren/3.png'),
      require('@/assets/img/project/app/wholeren/4.png'),
      require('@/assets/img/project/app/wholeren/5.png'),
      require('@/assets/img/project/app/wholeren/6.png'),
      require('@/assets/img/project/app/wholeren/7.png'),
      require('@/assets/img/project/app/wholeren/8.png'),
      require('@/assets/img/project/app/wholeren/9.png'),
      require('@/assets/img/project/app/wholeren/10.png'),
      require('@/assets/img/project/app/wholeren/11.png'),
      require('@/assets/img/project/app/wholeren/12.png'),
      require('@/assets/img/project/app/wholeren/13.png'),
      require('@/assets/img/project/app/wholeren/14.png'),
      require('@/assets/img/project/app/wholeren/15.png'),
      require('@/assets/img/project/app/wholeren/16.png'),
      require('@/assets/img/project/app/wholeren/17.png'),
      require('@/assets/img/project/app/wholeren/18.png'),
      require('@/assets/img/project/app/wholeren/19.png'),
      require('@/assets/img/project/app/wholeren/20.png'),
      require('@/assets/img/project/app/wholeren/21.png'),
      require('@/assets/img/project/app/wholeren/22.png'),
      require('@/assets/img/project/app/wholeren/23.png'),
      require('@/assets/img/project/app/wholeren/24.png'),
      require('@/assets/img/project/app/wholeren/25.png'),
      require('@/assets/img/project/app/wholeren/26.png'),
    ],
  },
  {
    name: 'RN Development Circle App',
    stack: ['react-native'],
    type: ['App'],
    label:
      'Using RN to develop commercial APP, mainly responsible for the home page, article details page page logic, online ios and Android platforms',
    thumb: require('@/assets/img/project/app/quanhu/thumb.png'),
    img: [
      require('@/assets/img/project/app/quanhu/thumb.png'),
      require('@/assets/img/project/app/quanhu/1.png'),
      require('@/assets/img/project/app/quanhu/2.png'),
      require('@/assets/img/project/app/quanhu/3.png'),
      require('@/assets/img/project/app/quanhu/4.png'),
      require('@/assets/img/project/app/quanhu/5.png'),
      require('@/assets/img/project/app/quanhu/6.png'),
      require('@/assets/img/project/app/quanhu/7.png'),
    ],
  },
  {
    name: 'RN Development Leisurely Point App',
    stack: ['react-native'],
    type: ['App'],
    label:
      'Using RN to develop commercial APP, mainly responsible for the home page, comments, likes and other functional modules, online on ios and Android platforms',
    thumb: require('@/assets/img/project/app/yryz/thumb.png'),
    img: [
      require('@/assets/img/project/app/yryz/thumb.png'),
      require('@/assets/img/project/app/yryz/1.png'),
      require('@/assets/img/project/app/yryz/2.png'),
      require('@/assets/img/project/app/yryz/3.png'),
      require('@/assets/img/project/app/yryz/4.png'),
      require('@/assets/img/project/app/yryz/5.png'),
      require('@/assets/img/project/app/yryz/6.png'),
      require('@/assets/img/project/app/yryz/7.png'),
      require('@/assets/img/project/app/yryz/8.png'),
      require('@/assets/img/project/app/yryz/9.png'),
      require('@/assets/img/project/app/yryz/10.png'),
      require('@/assets/img/project/app/yryz/11.png'),
      require('@/assets/img/project/app/yryz/12.png'),
      require('@/assets/img/project/app/yryz/13.png'),
    ],
  },
  {
    name: 'Huren service applet',
    stack: ['taro'],
    type: ['MiniProgram'],
    label:
      "The company's business introduction mini-program developed for all C-end users, and publishes WeChat and Toutiao at the same time",
    thumb: require('@/assets/img/project/applets/wholeren-fuwu/thumb.png'),
    img: [
      require('@/assets/img/project/applets/wholeren-fuwu/thumb.png'),
      require('@/assets/img/project/applets/wholeren-fuwu/1.png'),
      require('@/assets/img/project/applets/wholeren-fuwu/2.png'),
      require('@/assets/img/project/applets/wholeren-fuwu/3.png'),
      require('@/assets/img/project/applets/wholeren-fuwu/4.png'),
    ],
  },
  {
    name: 'Houren Study Abroad WeChat Mini Program',
    stack: ['taro'],
    type: ['MiniProgram'],
    label:
      'For all C-end users, the epidemic data of American universities is provided, and a richer web version is developed through nuxt',
    thumb: require('@/assets/img/project/applets/wholeren-liuxue/thumb.png'),
    img: [
      require('@/assets/img/project/applets/wholeren-liuxue/thumb.png'),
      require('@/assets/img/project/applets/wholeren-liuxue/1.png'),
      require('@/assets/img/project/applets/wholeren-liuxue/2.png'),
      require('@/assets/img/project/applets/wholeren-liuxue/3.png'),
    ],
  },
  {
    name: 'Hou Ren Student Center WeChat Mini Program',
    stack: ['taro'],
    type: ['MiniProgram'],
    label: 'For all paid users, provide daily management, service tracking, application feedback and other functions',
    thumb: require('@/assets/img/project/applets/wholeren-student/thumb.png'),
    img: [
      require('@/assets/img/project/applets/wholeren-student/thumb.png'),
      require('@/assets/img/project/applets/wholeren-student/1.png'),
      require('@/assets/img/project/applets/wholeren-student/2.png'),
      require('@/assets/img/project/applets/wholeren-student/3.png'),
      require('@/assets/img/project/applets/wholeren-student/4.png'),
      require('@/assets/img/project/applets/wholeren-student/5.png'),
      require('@/assets/img/project/applets/wholeren-student/6.png'),
      require('@/assets/img/project/applets/wholeren-student/7.png'),
      require('@/assets/img/project/applets/wholeren-student/8.png'),
      require('@/assets/img/project/applets/wholeren-student/9.png'),
      require('@/assets/img/project/applets/wholeren-student/10.png'),
    ],
  },
  {
    name: 'Houren Tutor Center WeChat Mini Program',
    stack: ['taro'],
    type: ['MiniProgram'],
    label: 'For company service tutors, it provides functions such as student management and service tracking',
    thumb: require('@/assets/img/project/applets/wholeren-teacher/thumb.png'),
    img: [
      require('@/assets/img/project/applets/wholeren-teacher/thumb.png'),
      require('@/assets/img/project/applets/wholeren-teacher/1.png'),
      require('@/assets/img/project/applets/wholeren-teacher/2.png'),
      require('@/assets/img/project/applets/wholeren-teacher/3.png'),
      require('@/assets/img/project/applets/wholeren-teacher/4.png'),
      require('@/assets/img/project/applets/wholeren-teacher/5.png'),
      require('@/assets/img/project/applets/wholeren-teacher/6.png'),
      require('@/assets/img/project/applets/wholeren-teacher/7.png'),
    ],
  },
  {
    name: 'Study in the U.S. Mentor Column',
    stack: ['taro'],
    type: ['MiniProgram'],
    label: 'For C-end users, provide study abroad information',
    thumb: require('@/assets/img/project/applets/wholeren-blog/thumb.png'),
    img: [
      require('@/assets/img/project/applets/wholeren-blog/thumb.png'),
      require('@/assets/img/project/applets/wholeren-blog/1.png'),
      require('@/assets/img/project/applets/wholeren-blog/2.png'),
      require('@/assets/img/project/applets/wholeren-blog/3.png'),
      require('@/assets/img/project/applets/wholeren-blog/4.png'),
      require('@/assets/img/project/applets/wholeren-blog/5.png'),
    ],
  },
  {
    name: 'fits-erp enterprise background management platform',
    stack: ['react', 'golang'],
    type: ['Website', 'Backend'],
    label: 'Customized enterprise background management platform for company business',
    thumb: require('@/assets/img/project/web/fits/thumb.png'),
    img: [
      require('@/assets/img/project/web/fits/thumb.png'),
      require('@/assets/img/project/web/fits/1.png'),
      require('@/assets/img/project/web/fits/2.png'),
      require('@/assets/img/project/web/fits/3.png'),
      require('@/assets/img/project/web/fits/4.png'),
      require('@/assets/img/project/web/fits/5.png'),
      require('@/assets/img/project/web/fits/6.png'),
    ],
  },
  {
    name: 'US Campus Epidemic Network',
    stack: ['vue', 'nuxt'],
    type: ['Website'],
    label:
      "In response to the US campus epidemic, provide epidemic data and school data. Guaranteed good seo' with nuxt",
    thumb: require('@/assets/img/project/web/covid/thumb.png'),
    img: [
      require('@/assets/img/project/web/covid/thumb.png'),
      require('@/assets/img/project/web/covid/1.png'),
      require('@/assets/img/project/web/covid/2.png'),
      require('@/assets/img/project/web/covid/3.png'),
      require('@/assets/img/project/web/covid/4.png'),
      require('@/assets/img/project/web/covid/5.png'),
      require('@/assets/img/project/web/covid/6.png'),
      require('@/assets/img/project/web/covid/7.png'),
      require('@/assets/img/project/web/covid/8.png'),
      require('@/assets/img/project/web/covid/9.png'),
      require('@/assets/img/project/web/covid/10.png'),
    ],
  },
  {
    name: 'American College Ranking Network',
    stack: ['vue', 'nuxt'],
    type: ['Website'],
    label: 'For c-end users, provide college ranking data, use nuxt to ensure good seo',
    thumb: require('@/assets/img/project/web/school/thumb.png'),
    img: [
      require('@/assets/img/project/web/school/thumb.png'),
      require('@/assets/img/project/web/school/1.png'),
      require('@/assets/img/project/web/school/2.png'),
    ],
  },
  {
    name: 'Order payment',
    stack: ['vue', 'nuxt'],
    type: ['Website'],
    label: 'User payment interface developed with vue',
    thumb: require('@/assets/img/project/web/shop/thumb.png'),
    img: [
      require('@/assets/img/project/web/shop/thumb.png'),
      require('@/assets/img/project/web/shop/1.png'),
      require('@/assets/img/project/web/shop/2.png'),
      require('@/assets/img/project/web/shop/3.png'),
      require('@/assets/img/project/web/shop/4.png'),
      require('@/assets/img/project/web/shop/5.png'),
    ],
  },
  {
    name: 'Teacher Growth Profile',
    stack: ['vue'],
    type: ['Website'],
    label: 'The background management system developed by vue',
    thumb: require('@/assets/img/project/web/teacher-admin/thumb.png'),
    img: [
      require('@/assets/img/project/web/teacher-admin/thumb.png'),
      require('@/assets/img/project/web/teacher-admin/1.png'),
      require('@/assets/img/project/web/teacher-admin/2.png'),
      require('@/assets/img/project/web/teacher-admin/3.png'),
      require('@/assets/img/project/web/teacher-admin/4.png'),
      require('@/assets/img/project/web/teacher-admin/5.png'),
      require('@/assets/img/project/web/teacher-admin/6.png'),
      require('@/assets/img/project/web/teacher-admin/7.png'),
      require('@/assets/img/project/web/teacher-admin/8.png'),
    ],
  },
  {
    name: 'music player',
    stack: ['vue'],
    type: ['Website'],
    label: 'Use the music player developed by vue (practice)',
    thumb: require('@/assets/img/project/web/music/thumb.png'),
    img: [
      require('@/assets/img/project/web/music/thumb.png'),
      require('@/assets/img/project/web/music/1.png'),
      require('@/assets/img/project/web/music/2.png'),
      require('@/assets/img/project/web/music/3.png'),
      require('@/assets/img/project/web/music/4.png'),
      require('@/assets/img/project/web/music/5.png'),
      require('@/assets/img/project/web/music/6.png'),
      require('@/assets/img/project/web/music/7.png'),
      require('@/assets/img/project/web/music/8.png'),
      require('@/assets/img/project/web/music/9.png'),
    ],
  },
  {
    name: 'Nw implements desktop program',
    stack: ['nw'],
    type: ['DesktopProgram'],
    label: 'Using the Xinjiang classroom courseware desktop program developed by nw. ',
    thumb: require('@/assets/img/project/computer/nw/thumb.png'),
    img: [
      require('@/assets/img/project/computer/nw/thumb.png'),
      require('@/assets/img/project/computer/nw/1.png'),
      require('@/assets/img/project/computer/nw/2.png'),
      require('@/assets/img/project/computer/nw/3.png'),
      require('@/assets/img/project/computer/nw/4.png'),
      require('@/assets/img/project/computer/nw/5.png'),
      require('@/assets/img/project/computer/nw/6.png'),
    ],
  },
  {
    name: 'Egret egret engine training hand and bird flying',
    stack: ['Egret'],
    type: ['MiniGame'],
    label:
      'Use Egret+Typescript to develop kindergarten games on Alpha Eggs (Little Bird Feifei is a hand training project)',
    thumb: require('@/assets/img/project/game/bird/thumb.png'),
    img: [require('@/assets/img/project/game/bird/thumb.png'), require('@/assets/img/project/game/bird/1.png')],
  },
  {
    name: 'Node implements WeChat public account background',
    stack: ['node'],
    type: ['Backend'],
    label: 'Use node to call jssdk, integrate WeChat login, payment and other functions on the web page',
    thumb: require('@/assets/img/project/bs/node/thumb.png'),
    img: [
      require('@/assets/img/project/app/sport/thumb.png'),
      require('@/assets/img/project/app/sport/1.png'),
      require('@/assets/img/project/app/sport/2.png'),
      require('@/assets/img/project/app/sport/3.png'),
    ],
  },
  {
    name: 'WeChat Enterprise Office Mini Program',
    stack: ['uniapp', 'java'],
    type: ['Backend', 'MiniProgram'],
    label: 'Using java+uniapp to implement small corporate office programs (practice)',
    thumb: require('@/assets/img/project/bs/java/thumb.png'),
    img: [
      require('@/assets/img/project/app/sport/thumb.png'),
      require('@/assets/img/project/app/sport/1.png'),
      require('@/assets/img/project/app/sport/2.png'),
      require('@/assets/img/project/app/sport/3.png'),
    ],
  },
];
const regex = {
  tel: /^1[3-9]\d{9}$/, // 手机号
  china: /^(\+?0?86-?)?1[345789]\d{9}$/, // 中国手机号
  americal: /^(\+?1)?[2-9]\d{2}[2-9](?!11)\d{6}$/, // 美国手机号
  email: /^[A-Za-z0-9]+([_\-.][A-Za-z0-9]+)*@([A-Za-z0-9-]+\.)+[A-Za-z]{2,6}$/i, // 邮箱
};

export { tabList, tabListEn, regex, projectList, projectListEn };
